import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const handleSubmit = async (event) => {
    //Para el evento submit
    event.preventDefault()

    //Paso el elemento que genera el evento (el formulario)
    let formulario = event.target; 
    //Creo un objeto con los datos del formulario.
    const data = {
      "fecha_inicio":formulario.fecha_inicio.value,
      "fecha_fin":formulario.fecha_fin.value,
      "arrendatario":formulario.arrendatario.value,
      "espacio":formulario.espacio.value
    }

    // paso el onjeto a formato Json
    const JSONdata = JSON.stringify(data)

    // direccion de la api para guardar
    const url = 'http://localhost/api/arriendos'

    // opciones de envio
    const options = {
      // Metodo post
      method: 'POST',
      // en formato JSON
      headers: {
        'Content-Type': 'application/json',
      },
      // El cuerpo(body) enviado es el objeto Json
      body: JSONdata,
    }

    // Envio infoirmacion y espero respuesta
    const response = await fetch(url, options)

    // Get the response data from server as JSON.
    // If server returns the name submitted, that means the form works.
    const result = await response.json()
    alert(`Is this your full name: ${result}`)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="continer">
        <div className="card">
          <div className="card-header">
            <h3>Crear Arriendos</h3>
          </div>
          <form  onSubmit={handleSubmit} > 
          <div className="card-body">           
            <div className="mb-3">
                <label className="form-label">Fecha Inicio</label>
                <input type="text" name="nombre" className="form-control"/>
            </div>         
            <div className="mb-3">
                <label className="form-label">fecha Fin</label>
                <input type="text" name="apellido" className="form-control"/>
            </div>         
            <div className="mb-3">
                <label className="form-label">Arrendatario</label>
                <input type="number" name="numero" className="form-control"/>
            </div>         
            <div className="mb-3">
                <label className="form-label">Espacio</label>
                <input type="email" name="correo" className="form-control"/>
            </div>         
          <div className="card-footer">
              <button className="btn btn-success w-100" type="submit">Enviar</button>
          </div>
          </form>
        </div>
      </main>
    </>
  )
}