import Head from "next/head";
import { Inter } from "@next/font/google";
import { use } from "react";
import Link from "next/link";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps(context) {
  // direccion de la api para guardar
  const url = "http://localhost/api/arriendos";

  // opciones de envio
  const options = {
    // Metodo post
    method: "GET",
    // en formato JSON
    headers: {
      "Content-Type": "application/json",
    },
  };

  // Envio infoirmacion y espero respuesta
  const response = await fetch(url, options);

  // Get the response data from server as JSON.
  // If server returns the name submitted, that means the form works.
  const data = await response.json();
  return { props: { data } };
}

function Page({ data }) {
  const router = useRouter();


  return (
    <>
      <Head>
        <title>Lista de Arrendatarios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <table className="table table-light table-bordered table-striped">
          <thead>
            <tr>
              <th>fecha_inicio</th>
              <th>fecha_fin</th>
              <th>arrendatario</th>
              <th>espacio</th>
            </tr>
          </thead>
          <tbody>
            {data.map((value, index) => {
              return (
                <tr key={index}>
                  <td>
                    {value.fecha_inicio} {value.fecha_fin}
                  </td>
                  <td>{value.arrendatario}</td>
                  <td>{value.espacio}</td>
                  <td>
                    <div className="btn-group">
                      <Link
                        href={"/arriendos/" + value._id}
                        className="btn btn-primary"
                      >
                        Editar
                      </Link>
                      <Link
                        href={"/arriendos/" + value._id}
                        className="btn btn-danger"
                      >
                        Eliminar
                      </Link>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
          <tfoot></tfoot>
        </table>
      </main>
    </>
  );
}

export default Page;
